services:
  webapp:
    image: laure-ferrando-website
    container_name: laure-ferrando
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    restart: unless-stopped
